### ISSUE TITLE
With more than one ToDo list we seem only to be able to add tasks to the first

### ISSUE THREAD

**Issue by Richard-Wilkinson** [AndreyVMarkelov/mailru-jira-plugins-todolist#10]
We have set up three separate ToDo lists on the Create, View, and View / Edit screens for a certain issue type. These appear one after the other (next to each other in the screen layout). 

Each ToDo has a default task list set, with 7 tasks in the first, 17 in the second and 2 in the third. They all display correctly when the issue is created and edited.

When we try to add extra tasks to the lists (not included in the default task list) this only works on the first list shown. For the other two lists, nothing happens when we click the Add ToDo button.

Thanks,

Richard

**Comment by Richard-Wilkinson** [comment]
We're on quite an old version of JIRA - JIRA v4.3 using ToDo list plugin 1.2 ...

**Comment by AndreyVMarkelov** [comment]
Hi,

Is it still actual for you?

**Comment by Richard-Wilkinson** [comment]
Hello,

Yes, it's still happening like this. As I said, we are on an old version of JIRA though.

Thanks,

Richard

**Comment by AndreyVMarkelov** [comment]
I will check it. I believe it is still compatible. If so, I will change the version. Wait, please, about a day.

**Comment by Richard-Wilkinson** [comment]
Thanks very much.

I’m attaching a screen shot to illustrate, if it helps. This is the part of our Create Issue screen showing the lists. The task lists are set up as default values for the parameters

I successfully added New task and New task 2 to the list “Pre-deployment tasks” using the Add ToDo button on this screen. But trying to add New task 3 to the “Deployment tasks” list underneath, the Add ToDo button on that list has no effect.

Thanks for looking at it,

Richard

---

Richard Wilkinson
Technical Author

**Comment by AndreyVMarkelov** [comment]
Done. Please, update, test and rate here: https://marketplace.atlassian.com/plugins/ru.mail.jira.plugins.todolist

**Comment by Richard-Wilkinson** [comment]
Thanks – that was quick!

I’ve downloaded and installed the update (v1.9.3) but need to restart in order to for the change to take effect. It may be later this evening or tomorrow before there’s a good moment to do this. I will let you know how it goes.

Richard

---

Richard Wilkinson
Technical Author

**Comment by AndreyVMarkelov** [comment]
Any updates?

**Comment by Richard-Wilkinson** [comment]
Sorry, we didn’t get to restart yesterday but we have a restart scheduled for this afternoon so I should be able to check it before the end of the day.

Thanks,

Richard

---

Richard Wilkinson
Technical Author

**Comment by Richard-Wilkinson** [comment]
Excellent - that has fixed it. New buttons too! Thanks very much.

Richard

**Comment by AndreyVMarkelov** [comment]
Could you rate here: https://marketplace.atlassian.com/plugins/ru.mail.jira.plugins.todolist :-)

**Comment by Richard-Wilkinson** [comment]
I’ve just done so. Thanks!

Richard

---

Richard Wilkinson
Technical Author

**Comment by AndreyVMarkelov** [comment]
Thanks!
