### ISSUE TITLE
Pressing Enter instead of clicking Add To List sometimes causes all items to disappear and list to stop working

### ISSUE THREAD

**Issue by Richard-Wilkinson** [AndreyVMarkelov/mailru-jira-plugins-todolist#6]
Hello,

One of our users reported the issue below on Google Chrome. This doesn't always happen but has been seen more than once.
1.  Click on Edit
2.  Enter list item
3.  Instead of clicking ‘Add to List’ hit ‘Enter’
4.  This sometimes causes all list items to disappear from the issue and for it to be impossible to add new items

After this, the list in that issue is unusable by anybody, not just the user who made the change.

Thanks,

Richard

**Comment by AndreyVMarkelov** [comment]
Will look at.

**Comment by AndreyVMarkelov** [comment]
I cannot reproduce. Please, get more info if bug still exists.
