### ISSUE TITLE
Error message when updating after deleting an item

### ISSUE THREAD

**Issue by SandroK** [AndreyVMarkelov/mailru-jira-plugins-todolist#9]
I get below error message when pressing "Update" after having deleted an item from the list. The issues I have tried this on has been created after installing the extension. Same with those, that have already been there. Again, everything is stored and update fine.

```
 Ausnahme: com.atlassian.jira.exception.DataAccessException: org.ofbiz.core.entity.GenericEntityException:
 while inserting: [GenericEntity:ChangeItem][newvalue,null][oldstring,test - ☐ zrdz3 - ☐ ][field,Akzeptanzkriterien]
 [id,10966][fieldtype,custom][newstring,test - ☐ ][oldvalue,null][group,10827] (SQL Exception while executing the 
 following:INSERT INTO changeitem (ID, groupid, FIELDTYPE, FIELD, OLDVALUE, OLDSTRING, NEWVALUE, 
 NEWSTRING) VALUES (?, ?, ?, ?, ?, ?, ?, ?) (Incorrect string value: '\xE2\x98\x90\x0Azr...' for column 
 'OLDSTRING' at row 1))
```

**Comment by AndreyVMarkelov** [comment]
Hi, I cannot reproduce.

Could you help me?

**Comment by SandroK** [comment]
I'll try :-) In the following sequence both errors occur:

This is what I do:
- Create new story and save without any todos
- Open editing window for story
- Type "test" into todo text field
- Press "+"
- Error 1 occurs (from the other issue), the item appears in the list though
- Press "Update", the saving indicator appears
- Error 2 occurs (this one)
- Press "Update" again and it closes and seems to save properly

This issue also occurs when I open the editing dialog, remove an item from the list and then try to update.
It does NOT occur however upon creating the story, then I can save properly without error.

That's it. Happy to give more info, but don't know what else I could tell you,

Regards,
Sandro

**Comment by AndreyVMarkelov** [comment]
What database do you use?

**Comment by SandroK** [comment]
It's MySQL: 5.5.32

Got the whole server info for you

Basis-URL   http://jira:8080
Systemdatum     Montag, 09 Sep 2013
Systemzeit  08:41:54 +0200
Aktuelles Arbeitsverzeichnis    /home/boss
Java-Version    1.7.0_25
Java-Hersteller     Oracle Corporation
JVM-Version     1.7
JVM-Hersteller  Oracle Corporation
JVM-Implementierungsversion     23.25-b01
Java-Laufzeit   Java(TM) SE Runtime Environment
Java VM     Java HotSpot(TM) 64-Bit Server VM
Benutzername    jira
Benutzerzeitzone    Europe/Berlin
Benutzer-Spracheinstellungen    Deutsch (Deutschland)
Systemverschlüsselung  UTF-8
Betriebssystem  Linux 3.2.0-51-generic
Betriebssystemarchitektur   amd64
Application Server Container    Apache Tomcat/7.0.29
Datenbanktyp    mysql
JNDI-Datenbankadresse   mysql jdbc:mysql://localhost:3306/jiradb?useUnicode=true&characterEncoding=UTF8&sessionVariables=storage_engine=InnoDB
Datenbank-URL   jdbc:mysql://localhost:3306/jiradb?useUnicode=true&characterEncoding=UTF8&sessionVariables=storage_engine=InnoDB
Datenbankversion    5.5.32-0ubuntu0.12.04.1
Datenbanktreiber    MySQL Connector Java mysql-connector-java-5.1.26 ( Revision: ${bzr.revision-id} )
Externe Benutzerverwaltung  AUS
JVM-Eingabeargumente    -Djava.util.logging.config.file=/opt/atlassian/jira/conf/logging.properties -XX:MaxPermSize=384m -Xms384m -Xmx768m -Djava.awt.headless=true -Datlassian.standalone=JIRA -Dorg.apache.jasper.runtime.BodyContentImpl.LIMIT_BUFFER=true -Dmail.mime.decodeparameters=true -Datlassian.plugins.enable.wait=300 -XX:+PrintGCDateStamps -Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager -Djava.endorsed.dirs=/opt/atlassian/jira/endorsed -Dcatalina.base=/opt/atlassian/jira -Dcatalina.home=/opt/atlassian/jira -Djava.io.tmpdir=/opt/atlassian/jira/temp
Geänderte Dateien  [Installationstyp: Standalone] jira-application.properties
Entfernte Dateien   [Installationstyp: Standalone] Es gibt keine entfernten Dateien

**Comment by AndreyVMarkelov** [comment]
I use "\u2611" and "\u2610" characters. Strange that your database cannot save

**Comment by SandroK** [comment]
You mean you are storing the status of the item as those characters? But we have a UTF8 encoded db, so that SHOULD actually not be the problem, right?

**Comment by AndreyVMarkelov** [comment]
Today I will public new version. Maybe it can help.

Or I can send you this version now to trying on. Bit I need your email)

**Comment by AndreyVMarkelov** [comment]
See new version on marketplace

**Comment by SandroK** [comment]
Got it! Works like a charm! Thank you! :-)

**Comment by AndreyVMarkelov** [comment]
I have updated documentation (a little bit in process). Please, look at.
